/*

.toFixed( ) - FORMATAÇÃO DE NÚMERO;
.PUSH - ADICIONA NO FINAL;
.POP - REMOVE ÚLTIMO DA LISTA;
.SHIFT - REMOVE PRIMEIRO DA LISTA; (DESLOCA O ÍNDICE)
.UNSHIFT - ADICIONA NO COMEÇO DA LISTA; (DESLOCA O PRIMEIRO ÍNDICE);
.CONCAT - CONCATENAR ARRAYS ;
.filter - Requer um function para ser executada;
.MAP - 
.REDUCE - 
*/
 