/*

.toFixed( ) - FORMATAÇÃO DE NÚMERO;
.PUSH - ADICIONA NO FINAL;
.POP - REMOVE ÚLTIMO DA LISTA;
.SHIFT - REMOVE PRIMEIRO DA LISTA; (DESLOCA O ÍNDICE)
.UNSHIFT - ADICIONA NO COMEÇO DA LISTA; (DESLOCA O PRIMEIRO ÍNDICE);
.CONCAT - CONCATENAR ARRAYS ;
.filter - Requer um function para ser executada;
.MAP - 
.REDUCE - 
\n - QUEBRA DE LINHA NO TEXTO;
\t- TAB ENTRE AS PALAVRAS;
floor - ARREDONDA O NÚMERO PARA BAIXO;
ceil - ARREDONDA O NÚMERO PRA CIMA;
MÉTODO TRIM - REMOVE TUDO QUE NÃO É TEXTO EM UMA STRING ( ESPAÇOS NO INÍCIO E O FIM DA STRING);
MÉTODO JOIN - ADICIONAR ITENS PARA FORMAR FRASES DINÂMICAS

*/
